import type { Metadata } from "next";
import { Inter, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "../../src/lib/utils";
import Footer from "../../components/footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FS Weather App",
  description: "Generated by Filip Sjöstrand",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen flex flex-col bg-background font-sans antialiased bg-cover bg-center bg-no-repeat",
          inter.variable
        )}
        style={{
          backgroundImage: "url('/images/bg-cloud_pexels-pixabay-314726.jpg')",
        }}
      >

        {/* Background Attribution Text */}
        <div className="absolute bottom-25 right-4 text-black text-base opacity-80 font-medium">
          Photo: Pixabay (pexels.com)
        </div>

        <main className="flex-1">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
